_wandb:
    value:
        cli_version: 0.21.4
        e:
            7054y6rmx6a8mg5vxhy6v8ia5wi7m6y5:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                args:
                    - --model-config
                    - model_config.yaml
                    - --train-config
                    - train_config.yaml
                    - --wandb-project
                    - nmt_experiments
                    - --wandb-run-name
                    - trans-small
                codePath: part1/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "143675174912"
                email: affanijaz@outlook.com
                executable: /Users/affanijaz/Documents/GitHub/cw2_2025_2026-students/.venv/bin/python
                git:
                    commit: 6360ddf3bff7067ac46ab0ecda6a7d59a7390ae7
                    remote: https://github.com/AffanI0/cw2_2025_2026-students.git
                host: Affans-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/affanijaz/Documents/GitHub/cw2_2025_2026-students/part1/train.py
                python: CPython 3.12.12
                root: /Users/affanijaz/Documents/GitHub/cw2_2025_2026-students/part1
                startedAt: "2025-11-07T15:01:39.649531Z"
                writerId: 7054y6rmx6a8mg5vxhy6v8ia5wi7m6y5
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.12
            "5": 0.21.4
            "12": 0.21.4
            "13": darwin-arm64
dev_batch_size:
    value: 128
dropout_rate:
    value: 0.2
embed_size:
    value: 16
hidden_size:
    value: 16
log_every:
    value: 10
lr:
    value: 0.001
lr_decay:
    value: 0.5
max_epoch:
    value: 30
max_num_trial:
    value: 5
patience:
    value: 1
seed:
    value: 0
train_batch_size:
    value: 32
uniform_init:
    value: 0.1
valid_niter:
    value: 2000
